### ISSUE TITLE
Everything seems broken on Firefox 119

### ISSUE THREAD

**Issue by LennyLizowzskiy** [cascadefox/cascade#109]
**Describe the bug**
I've just installed the theme in Firefox 119 and also added Tab Center add-on.
Theme's color palette doesn't change when I change browser theme.
TCR displays black text on black background.
There's also white text on light background in search bar when you're typing something there

**Screenshots** (optional)
![image](https://github.com/andreasgrafen/cascade/assets/46971551/ce8d522d-7dfa-453c-a15f-2e056e446671)

**Comment by LennyLizowzskiy** [comment]
Oh, also there's a chrome folder contents. Nothing has been changed in the `cascade-config.css` - absolutely stock settings. 
![image](https://github.com/andreasgrafen/cascade/assets/46971551/d40e5ca3-9c09-498d-b4d3-acc903d03e2e)

**Comment by vanitysys28** [comment]
Did you make sure to remove everything from the navigation bar area?

As per README: 

> To do so rightclick your bar and go into the customisation settings. You can move all the icons freely which allows you to place your Addons within the Personal Toolbar for example.
